# Generated by Django 5.2.6 on 2025-09-23 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('patient', '0006_alter_patient_mobile_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_type',
            field=models.CharField(help_text='MIME type of the document (e.g., application/pdf, image/jpeg).', max_length=150),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the document record was created.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(help_text='Category or type of the document (e.g., Lab Report, Prescription, Scan).', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='filename',
            field=models.CharField(help_text='Original filename of the uploaded file (e.g., blood_test_report.pdf).', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='gcs_key',
            field=models.CharField(help_text='Unique key or path used to store and retrieve the file from Google Cloud Storage.', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_uploaded',
            field=models.BooleanField(default=False, help_text='Indicates whether the document has been successfully uploaded to storage.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The staff member (e.g., doctor, admin) who uploaded or owns this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(help_text='The patient this document is associated with. Deleting the patient will also delete this document.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='document',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes (useful for validating upload limits).', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the document record was last updated.'),
        ),
    ]
