# Generated by Django 5.2.6 on 2025-10-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_document_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_uploaded',
        ),
    ]
