# Generated by Django 5.2.6 on 2025-10-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_document_is_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the document.', null=True),
        ),
    ]
