# Generated by Django 5.2.6 on 2025-10-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_uploaded',
            field=models.BooleanField(default=False, help_text='Indicates whether the document has been successfully uploaded to storage.'),
        ),
    ]
