# Generated by Django 5.2.6 on 2025-09-23 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0006_alter_patient_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_instructions', models.TextField(blank=True, help_text='Any special instructions for the patient.', null=True)),
                ('follow_up_date', models.DateField(blank=True, help_text='Optional follow-up date for the patient.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='The patient for whom this prescription is created.', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the medicine (e.g., Arnica 30C).', max_length=255)),
                ('dosage', models.CharField(help_text='Dosage instructions (e.g., 5 drops).', max_length=100)),
                ('frequency', models.CharField(help_text='How often the medicine should be taken (e.g., 3 times a day).', max_length=100)),
                ('duration', models.CharField(help_text='How long the medicine should be taken (e.g., 15 days).', max_length=100)),
                ('prescription', models.ForeignKey(help_text='The prescription this medicine belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescription.prescription')),
            ],
        ),
    ]
