"""
Django settings for pms_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k^l$6s!6@$d@r)984l69dbz1w+p4oj7ta^o^)re6w_m!knw%$k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["backend.jsonformatters.online","127.0.0.1","localhost"]

CSRF_TRUSTED_ORIGINS = [
    "https://backend.jsonformatters.online",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'drf_spectacular',
    'corsheaders',
    'backend_apps.patient',
    'backend_apps.otp',
    'backend_apps.document',
    'backend_apps.accounts',
    'backend_apps.prescription',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pms_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pms_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='mydb'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "accounts.PMSUser"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DRF & JWT configuration
REST_FRAMEWORK = {
    # 🔑 Authentication: use JWT for securing API requests
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # 🔒 Permissions: require authentication by default for all endpoints
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    # 📄 Pagination: use page-number pagination with default page size of 20
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    # 🔎 Filtering, searching, and ordering support for querysets
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # field-based filtering
        'rest_framework.filters.SearchFilter',                # full-text search on specified fields
        'rest_framework.filters.OrderingFilter',              # ordering via ?ordering=field
    ],

    # 🎨 Response rendering: only allow JSON responses (no browsable API in production)
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],

    # 📝 Request parsing: support JSON, file uploads (multipart), and form data
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',       # parse application/json
        'rest_framework.parsers.MultiPartParser',  # parse multipart/form-data (file upload)
        'rest_framework.parsers.FormParser',       # parse regular HTML form data
    ],

    # ⚠️ Custom error handling: central place for formatting API exceptions
    'EXCEPTION_HANDLER': 'pms_backend.exceptions.custom_exception_handler',

    # 📘 API schema generation: use drf-spectacular to generate OpenAPI/Swagger docs
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# API Documentation settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Patient Management System API',
    'DESCRIPTION': 'A comprehensive API for managing patients, documents, and authentication',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'TAGS': [
        {'name': 'Authentication', 'description': 'User authentication and authorization'},
        {'name': 'Patients', 'description': 'Patient management operations'},
        {'name': 'Documents', 'description': 'Document upload and management'},
        {'name': 'OTP', 'description': 'One-time password operations'},
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# OTP configuration (env-driven with sane defaults)
OTP_CODE_LENGTH = int(os.getenv('OTP_CODE_LENGTH', '6'))
OTP_TTL_SECONDS = int(os.getenv('OTP_TTL_SECONDS', '300'))  # 5 minutes
OTP_MAX_ATTEMPTS = int(os.getenv('OTP_MAX_ATTEMPTS', '5'))
OTP_RESEND_COOLDOWN_SECONDS = int(os.getenv('OTP_RESEND_COOLDOWN_SECONDS', '30'))
OTP_EMAIL_SUBJECT = os.getenv('OTP_EMAIL_SUBJECT', 'Your verification code')
OTP_EMAIL_TEMPLATE = os.getenv('OTP_EMAIL_TEMPLATE', 'Your OTP code is: {code}')
OTP_REQUIRE_PROVIDER_CONFIG = os.getenv('OTP_REQUIRE_PROVIDER_CONFIG', 'false').lower() in {'1', 'true', 'yes'}

# Email configuration
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@example.com')
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587')) if os.getenv('EMAIL_HOST') else 587
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() in {'1', 'true', 'yes'}
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() in {'1', 'true', 'yes'}

# GCP / GCS configuration
GCS_BUCKET_NAME = os.getenv('GCS_BUCKET_NAME', '')
GCS_UPLOAD_PREFIX = os.getenv('GCS_UPLOAD_PREFIX', 'uploads/')
GCS_SIGNED_URL_EXPIRE_SECONDS = int(os.getenv('GCS_SIGNED_URL_EXPIRE_SECONDS', str(15 * 60)))
GCS_SIGNED_GET_EXPIRE_SECONDS = int(os.getenv('GCS_SIGNED_GET_EXPIRE_SECONDS', str(60 * 60)))

# JWT configuration
from datetime import timedelta
SIMPLE_JWT = {
    # ⏳ Access token lifetime (short-lived, usually minutes)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),

    # 🔄 Refresh token lifetime (longer-lived, usually days/weeks)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # Whether a refresh token can be reused or should be rotated
    'ROTATE_REFRESH_TOKENS': True,

    # If old refresh tokens should be blacklisted when rotated
    'BLACKLIST_AFTER_ROTATION': True,
}