# Generated by Django 5.2.6 on 2025-09-23 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='mobile_number',
        ),
    ]
