# Generated by Django 5.2.6 on 2025-09-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
