# Generated by Django 5.2.6 on 2025-09-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
