# Generated by Django 5.2.6 on 2025-09-28 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_remove_patient_last_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('deceased', 'Deceased')], default='active', help_text='Current status of the patient', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['doctor', 'status'], name='patient_pat_doctor__f55575_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['mobile_number'], name='patient_pat_mobile__f49ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status'], name='patient_pat_status_358d3c_idx'),
        ),
    ]
