# Generated by Django 5.2.6 on 2025-09-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_patient_status_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
    ]
