# Generated by Django 5.2.6 on 2025-10-01 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_remove_patient_date_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('doctor', 'mobile_number'), name='unique_doctor_patient_mobile'),
        ),
    ]
